# 中文字体
FROM openjdk:8-jre-alpine
RUN echo "http://mirrors.cloud.tencent.com/alpine/v3.15/main" > /etc/apk/repositories \
    && echo "http://mirrors.cloud.tencent.com/alpine/v3.15/community/" >> /etc/apk/repositories \
    && apk update upgrade \
    && apk add --no-cache procps unzip curl bash tzdata \
    && apk add ttf-dejavu \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && rm -rf /var/cache/apk/*
